### PR TITLE
Update the doc and test cases

### PR DESCRIPTION
**Pull request by jianyicheng**

### CODE REVIEW

**Comment by jianyicheng** [comment]
@dereklai1 I saw you made an PR here: https://github.com/DeepWok/mase/pull/199

We might have merged your previous code here... Could you merge this to your branch and try to point your PR to `fix/tests` instead of `main`? Thanks!

**Comment by dereklai1** [comment]
Yeah sure, I won't have my laptop for a week but I'll change it and fix up the rest of the branch when I'm back.

**Comment by jianyicheng** [comment]
Amazing. Thanks!

**Comment by Aaron-Zhao123** [comment]
@dereklai1 a bit of warning though, there is a huge refactor including a few file structure changes... I am sorry if this makes your life slightly harder than it should have been.

**Pull request merged**
