### PR TITLE
Suggestion: Add a nix derivation for better environment reproducibility

### PR DESCRIPTION
**Pull request by JoachimSand**
## Motivation
Many students had issues with wrong torch versions, CUDA not being available etc. These issues can be hard to fix depending on the local environment of the student. Additionally, these issues tend to waste a lot of time for the student and the GTA attempting to help solve it. 

As such, for future iterations of the course it might be worth including a `nix` [derivation shell](https://nixos.wiki/wiki/Development_environment_with_nix-shell) to the project for the sake of stability and reproducibility across platforms. A nix derivation would be able to explicitly state some of the system-level dependencies that some of the python packages in `requirements.txt` (implicitly) rely upon (e.g. CUDA). Additionally, one could add nix packages such as `svls` which in general would be useful when developing for MASE.

Finally, this would mean the _only_ prerequisite for getting MASE up and running would be an installation of the `nix` package manager.

## Details
A `nix` derivation would just be a `shell.nix` file in the root of the MASE repo. I wrote a derivation for myself during the course, and it served me well across 4 different machines. I have included it in this PR as an example.

To initialize the `nix` environment for mase, first install the `nix` [package manager](https://nixos.org/download/#download-nix). Then simply enter the `nix` environment by running `nix-shell` in the MASE repo directory containing the `shell.nix` file. This will enter a nix shell with:
- A fully working MASE environment initialized. 
- Ensure transitive binary requirements such as `libzip`, `libxml2` and `mesa` are installed. 
- `verible`, `verilator` and `svls` are automatically installed.
- PYTHONPATH extended with the machop directory.
- For full compatibility, a local virtual env is used to install the rest of the packages from `requirements.txt`. This means `requirements.txt` can be extended as usual and the `nix` environment will almost certainly still work.

### CODE REVIEW

**Comment by jianyicheng** [comment]
Thanks @JoachimSand. I agree both works.

I think a better place to store this script is to put it under this repo:  https://github.com/jianyicheng/mase-docker
(Of course the name of the repo needs to be changed...)

Unfortunately, we are a bit overloaded at the moment but it would be nice to have nix option there and integrated into GitHub CI.
Thanks again for the contribution! Would you mind creating a PR to merge there?

**Comment by ymherklotz** [comment]
One suggestion from the nix point of view would be to pin a specific `nixpkgs` version, otherwise building can become quite unreliable, and it's one of the strong points of nix.  You can do that for example using the following:

```nix
import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/8dd8bd8be74879f9f7919b16a4cb5ab2a75f18e5.tar.gz") {};
```

Instead of `import <nixpkgs> {};`, (with the hash changed to a recent unstable nixpkgs commit).

**Comment by jianyicheng** [comment]
Sorry. This PR was closed accidentally because I was changing the main branch...

**Comment by JoachimSand** [comment]
> One suggestion from the nix point of view would be to pin a specific `nixpkgs` version, otherwise building can become quite unreliable, and it's one of the strong points of nix. You can do that for example using the following:
> 
> ```nix
> import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/8dd8bd8be74879f9f7919b16a4cb5ab2a75f18e5.tar.gz") {};
> ```
> 
> Instead of `import <nixpkgs> {};`, (with the hash changed to a recent unstable nixpkgs commit).

Great point - should have thought of that myself!

@jianyicheng I opened [a corresponding PR](https://github.com/jianyicheng/mase-docker/pull/20) in the MASE docker repo. Like @ymherklotz suggested, this shell is now pinned to a stable version of nixpkgs (the most recent stable commit in 23.11). I just tested this locally and everything still works as intended.

**Comment by jianyicheng** [comment]
@JoachimSand Amazing! Thanks for this!

It may take a while for the PR to get merged, as you can see we started refactoring on the code base...

**Comment by Aaron-Zhao123** [comment]
I think `shell.nix` should live in this repository, instead of the docker one.

However, it seems like putting all cuda dependancies on nix is a better idea -- for machines that do not have gpu capability, this installation seems to fail? 

We might just use `nix` to lock in basic functions and use @pgimenes 's setuptool flow to install? 

So I tweaked the `.nix` slightly


```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-unstable";
  pkgs = import nixpkgs { config = { allowUnfree = true; cudaSupport = true; nvidia.acceptLicense = true;}; overlays = []; };
in

let
  pythonPackages = pkgs.python311Packages;
in pkgs.mkShellNoCC {
  venvDir = "./.venv";
  packages = with pkgs; [
    # Python 3.11
    pythonPackages.python
    pythonPackages.pip
    # This executes some shell code to initialize a venv in $venvDir before
    # dropping into the shell
    # TODO: consider use setuptoolsBuildHook, as documented in https://nixos.org/manual/nixpkgs/stable/#python
    pythonPackages.venvShellHook

    # houskeeping 
    git
    neovim
    glib
  ];
  postShellHook = ''
    # install mase as a package
    python3 -m pip install .
  '';
}
```

I have tested this on both `x86-darwin` (mac) and `x86-linux` (gpu-enabled), and have tested using 
```sh
python -c "import torch; print(torch.__version__, torch.__file__)"
```

**Comment by Aaron-Zhao123** [comment]
Moving this to #190

**Pull request closed without merging**
